# Generated by Django 4.2.2 on 2023-06-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='hexcolor',
            field=models.CharField(default='#ffffff', max_length=7, verbose_name='цвет'),
        ),
    ]
