# Generated by Django 4.2.2 on 2023-06-11 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_tag_hexcolor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='hexcolor',
            new_name='color',
        ),
    ]
