# Generated by Django 3.2.19 on 2023-07-05 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_ingredients_alter_recipe_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(help_text='Прикрепите изображение', upload_to='recipes/', verbose_name='Изображение'),
        ),
    ]
