# Generated by Django 4.2.2 on 2023-06-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_recipeingredient_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeIngredient',
            new_name='RecipeIngridient',
        ),
        migrations.RemoveConstraint(
            model_name='recipeingridient',
            name='recipe_ingredient_exists',
        ),
        migrations.AddConstraint(
            model_name='recipeingridient',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingridient'), name='recipe_ingridient_exists'),
        ),
    ]
