# Generated by Django 4.2.2 on 2023-06-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_recipeingredient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='measurement_unit',
            field=models.CharField(default='null', max_length=100, verbose_name='Единица измерения'),
            preserve_default=False,
        ),
    ]
