# Generated by Django 4.2.2 on 2023-06-12 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_recipeingredient_measurement_unit'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favoriteslist',
            name='unique_favorites',
        ),
        migrations.RemoveConstraint(
            model_name='shoppinglist',
            name='unique_recipes',
        ),
        migrations.RenameField(
            model_name='favoriteslist',
            old_name='recipes',
            new_name='recipe',
        ),
        migrations.RemoveField(
            model_name='shoppinglist',
            name='recipes',
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shopping_lists', to='recipes.recipe', verbose_name='рецепт из списка покупок'),
        ),
        migrations.AddConstraint(
            model_name='favoriteslist',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_favorites'),
        ),
        migrations.AddConstraint(
            model_name='shoppinglist',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_recipe'),
        ),
    ]
