# Generated by Django 4.2.2 on 2023-06-12 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_customrecipeingredient_alter_ingredient_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomRecipeIngredient',
            new_name='RecipeIngredient',
        ),
    ]
