# Generated by Django 4.2.2 on 2023-06-12 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_remove_ingredient_amount_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeIngredient',
            new_name='CustomRecipeIngredient',
        ),
    ]
