# Generated by Django 4.2.2 on 2023-06-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_rename_recipeingredient_customrecipeingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='amount',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='measurement_unit',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Единица измерения'),
        ),
    ]
